// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using monopoly_backend.Data;

#nullable disable

namespace monopoly_backend.Migrations
{
    [DbContext(typeof(MonopolyDbContext))]
    [Migration("20260122164842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("monopoly_backend.Models.Entities.Board", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.DiceRoll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Die1")
                        .HasColumnType("int");

                    b.Property<int>("Die2")
                        .HasColumnType("int");

                    b.Property<DateTime>("RolledAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TurnId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TurnId")
                        .IsUnique();

                    b.ToTable("DiceRolls");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CurrentTurnPlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Round")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentTurnPlayerId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Money")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Position")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TurnsInJail")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ColorGroup")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Rent")
                        .HasColumnType("int");

                    b.Property<Guid>("TileId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("TileId")
                        .IsUnique();

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BoardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Turn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Board", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Game", "Game")
                        .WithOne("Board")
                        .HasForeignKey("monopoly_backend.Models.Entities.Board", "GameId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.DiceRoll", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Turn", "Turn")
                        .WithOne("DiceRoll")
                        .HasForeignKey("monopoly_backend.Models.Entities.DiceRoll", "TurnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Turn");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Game", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Player", "CurrentTurnPlayer")
                        .WithMany()
                        .HasForeignKey("CurrentTurnPlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CurrentTurnPlayer");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Player", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Game", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Property", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Player", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("monopoly_backend.Models.Entities.Tile", "Tile")
                        .WithOne("Property")
                        .HasForeignKey("monopoly_backend.Models.Entities.Property", "TileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Tile");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Tile", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Board", "Board")
                        .WithMany("Tiles")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Turn", b =>
                {
                    b.HasOne("monopoly_backend.Models.Entities.Game", "Game")
                        .WithMany("Turns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("monopoly_backend.Models.Entities.Player", "Player")
                        .WithMany("Turns")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Board", b =>
                {
                    b.Navigation("Tiles");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Game", b =>
                {
                    b.Navigation("Board");

                    b.Navigation("Players");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Player", b =>
                {
                    b.Navigation("Properties");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Tile", b =>
                {
                    b.Navigation("Property");
                });

            modelBuilder.Entity("monopoly_backend.Models.Entities.Turn", b =>
                {
                    b.Navigation("DiceRoll");
                });
#pragma warning restore 612, 618
        }
    }
}
